export const SPREADSHEET_LIST_REQUEST = 'SPREADSHEET_LIST_REQUEST'
export const SPREADSHEET_LIST_SUCCESS = 'SPREADSHEET_LIST_SUCCESS'
export const SPREADSHEET_LIST_FAIL = 'SPREADSHEET_LIST_FAIL'
export const SPREADSHEET_LIST_RESET = 'SPREADSHEET_LIST_RESET'

export const SPREADSHEET_DETAILS_REQUEST = 'SPREADSHEET_DETAILS_REQUEST'
export const SPREADSHEET_DETAILS_SUCCESS = 'SPREADSHEET_DETAILS_SUCCESS'
export const SPREADSHEET_DETAILS_FAIL = 'SPREADSHEET_DETAILS_FAIL'